{{- if not .Values.livebox.adminPassword.secretKeyRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livebox-exporter.fullname" . }}-admin
  labels:
    {{- include "livebox-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.livebox.adminPassword.value | b64enc }}
{{- end }}